project:
  type: manuscript
  render:
    - thesis.qmd
    - notebooks/04_population_qc.qmd
    - notebooks/05_descriptive_plots.qmd
    - notebooks/06_correlation.qmd
  output-dir: _manuscript

execute-dir: project

execute:
  cache: true
  freeze: auto
  echo: false
  warning: false
  message: false

format:
  html:
    toc: true
    toc-depth: 3
    theme: slate
    comments:
      hypothesis: true
  pdf:
    pdf-engine: xelatex
    toc: true
    number-sections: true
    papersize: a4
    geometry: margin=1in
    fig-format: pdf
    tbl-cap-location: top

bibliography: thesis_ref.bib

manuscript:
  article: thesis.qmd
  notebooks:
    - notebook: notebooks/04_population_qc.qmd
      title: Population QC
    - notebook: notebooks/05_descriptive_plots.qmd
      title: Descriptive plots
    - notebook: notebooks/06_correlation.qmd
      title: Correlation analysis
