project:
  type: manuscript
  render:
    - thesis.qmd

  output-dir: _manuscript

execute-dir: project
engine: knitr

execute:
  cache: true
  freeze: auto
  echo: false
  warning: false
  message: false

format:
  html:
    toc: true
    toc-depth: 3
    theme: slate
    comments:
      hypothesis: true
  pdf:
    pdf-engine: xelatex
    toc: true
    number-sections: true
    papersize: a4
    geometry: margin=1in
    fig-format: pdf
    tbl-cap-location: top

bibliography: thesis_ref.bib

manuscript:
  article: thesis.qmd
