project:
  type: manuscript

render:
  - thesis.qmd
  - notebooks/04_population_qc.qmd
  - notebooks/05_descriptive_plot.qmd
  - notebooks/06_correlation.qmd

execute:
  dir: "." 
  freeze: auto   

format:
  html:
    toc: true
    toc-depth: 3
    theme: slate
    comments:
      hypothesis: true
  pdf:
    toc: true
    number-sections: true
    papersize: a4
    geometry: "margin=1in"

    
manuscript:
  article: thesis.qmd   
  notebooks:    
    - notebook: notebooks/04_population_qc.qmd
      title: Population QC
    - notebook: notebooks/05_descriptive_plot.qmd
      title: Descriptive plots
    - notebook: notebooks/06_correlation.qmd
      title: Correlation analysis