project:
  type: manuscript

execute:
  freeze: auto

format:
  html:
    toc: true
    theme: cosmo
    comments:
      hypothesis: true

manuscript:
  article: proposal.qmd
  # resources: 
  #- ..

bibliography: proposal_ref.bib
link-citations: true