project:
  type: manuscript


format:
  html:
    toc: true
    theme: spacelab
    comments:
      hypothesis: true

manuscript:
  article: proposal.qmd
  # resources: 
  #- ..

bibliography: proposal_ref.bib