# Needed packages for the analysis
suppressPackageStartupMessages({
  library(styler)
  library(rnaturalearth)
  library(tidyverse)
  library(lubridate)
  library(sf)
  library(viridis)
  library(broom)
  library(purrr)
  library(ggrepel)
  library(kableExtra)
  library(scales)
  library(stringr)
  library(here)
  library(forcats)
})
